import { createColumnHelper } from '@tanstack/react-table';

import { Box, Typography } from '@mui/material';

import { MaterialType, type IProduct } from './types';

export function createData(
  imageUrl: string,
  height: string,
  material: string,
  materialType: MaterialType,
  name: string,
  price: string,
  stock: string,
  weight: string,
): IProduct {
  return {
    imageUrl,
    height,
    material,
    materialType,
    name,
    price,
    stock,
    weight,
  };
}

export const data: IProduct[] = [
  createData(
    'https://via.placeholder.com/150',
    '32 cm',
    'Plastic',
    MaterialType.ManufactoringPart,
    'Product 1',
    '$15.23',
    '48',
    '2.34 kg',
  ),
  createData(
    'https://via.placeholder.com/150',
    '45 cm',
    'Metal',
    MaterialType.Product,
    'Product 2',
    '$35.67',
    '87',
    '4.56 kg',
  ),
  createData(
    'https://via.placeholder.com/150',
    '78 cm',
    'Wood',
    MaterialType.PurchasingPart,
    'Product 3',
    '$58.12',
    '32',
    '3.89 kg',
  ),
  createData(
    'https://via.placeholder.com/150',
    '90 cm',
    'Plastic',
    MaterialType.ManufactoringPart,
    'Product 4',
    '$90.45',
    '21',
    '6.78 kg',
  ),
  createData(
    'https://via.placeholder.com/150',
    '12 cm',
    'Metal',
    MaterialType.Product,
    'Product 5',
    '$22.34',
    '76',
    '1.45 kg',
  ),
  createData(
    'https://via.placeholder.com/150',
    '34 cm',
    'Wood',
    MaterialType.PurchasingPart,
    'Product 6',
    '$49.99',
    '54',
    '5.67 kg',
  ),
  createData(
    'https://via.placeholder.com/150',
    '23 cm',
    'Plastic',
    MaterialType.ManufactoringPart,
    'Product 7',
    '$19.56',
    '98',
    '2.12 kg',
  ),
  createData(
    'https://via.placeholder.com/150',
    '56 cm',
    'Metal',
    MaterialType.Product,
    'Product 8',
    '$47.88',
    '65',
    '4.23 kg',
  ),
  createData(
    'https://via.placeholder.com/150',
    '78 cm',
    'Wood',
    MaterialType.PurchasingPart,
    'Product 9',
    '$83.45',
    '12',
    '7.89 kg',
  ),
  createData(
    'https://via.placeholder.com/150',
    '67 cm',
    'Plastic',
    MaterialType.ManufactoringPart,
    'Product 10',
    '$55.34',
    '49',
    '6.12 kg',
  ),
  createData(
    'https://via.placeholder.com/150',
    '45 cm',
    'Metal',
    MaterialType.Product,
    'Product 11',
    '$33.21',
    '85',
    '3.45 kg',
  ),
  createData(
    'https://via.placeholder.com/150',
    '23 cm',
    'Wood',
    MaterialType.PurchasingPart,
    'Product 12',
    '$29.89',
    '74',
    '2.89 kg',
  ),
  createData(
    'https://via.placeholder.com/150',
    '56 cm',
    'Plastic',
    MaterialType.ManufactoringPart,
    'Product 13',
    '$46.78',
    '38',
    '5.23 kg',
  ),
  createData(
    'https://via.placeholder.com/150',
    '89 cm',
    'Metal',
    MaterialType.Product,
    'Product 14',
    '$91.23',
    '50',
    '9.34 kg',
  ),
  createData(
    'https://via.placeholder.com/150',
    '34 cm',
    'Wood',
    MaterialType.PurchasingPart,
    'Product 15',
    '$40.56',
    '22',
    '3.12 kg',
  ),
  createData(
    'https://via.placeholder.com/150',
    '90 cm',
    'Plastic',
    MaterialType.ManufactoringPart,
    'Product 16',
    '$78.45',
    '67',
    '8.45 kg',
  ),
  createData(
    'https://via.placeholder.com/150',
    '12 cm',
    'Metal',
    MaterialType.Product,
    'Product 17',
    '$13.89',
    '59',
    '1.23 kg',
  ),
  createData(
    'https://via.placeholder.com/150',
    '45 cm',
    'Wood',
    MaterialType.PurchasingPart,
    'Product 18',
    '$37.12',
    '42',
    '3.78 kg',
  ),
  createData(
    'https://via.placeholder.com/150',
    '67 cm',
    'Plastic',
    MaterialType.ManufactoringPart,
    'Product 19',
    '$59.67',
    '31',
    '6.23 kg',
  ),
  createData(
    'https://via.placeholder.com/150',
    '78 cm',
    'Metal',
    MaterialType.Product,
    'Product 20',
    '$62.89',
    '80',
    '7.34 kg',
  ),
  createData(
    'https://via.placeholder.com/150',
    '56 cm',
    'Wood',
    MaterialType.PurchasingPart,
    'Product 21',
    '$45.12',
    '47',
    '5.78 kg',
  ),
  createData(
    'https://via.placeholder.com/150',
    '23 cm',
    'Plastic',
    MaterialType.ManufactoringPart,
    'Product 22',
    '$18.45',
    '92',
    '2.56 kg',
  ),
  createData(
    'https://via.placeholder.com/150',
    '90 cm',
    'Metal',
    MaterialType.Product,
    'Product 23',
    '$82.34',
    '73',
    '9.78 kg',
  ),
  createData(
    'https://via.placeholder.com/150',
    '12 cm',
    'Wood',
    MaterialType.PurchasingPart,
    'Product 24',
    '$11.23',
    '36',
    '1.34 kg',
  ),
  createData(
    'https://via.placeholder.com/150',
    '34 cm',
    'Plastic',
    MaterialType.ManufactoringPart,
    'Product 25',
    '$36.78',
    '54',
    '3.45 kg',
  ),
  createData(
    'https://via.placeholder.com/150',
    '45 cm',
    'Metal',
    MaterialType.Product,
    'Product 26',
    '$41.56',
    '67',
    '4.12 kg',
  ),
  createData(
    'https://via.placeholder.com/150',
    '78 cm',
    'Wood',
    MaterialType.PurchasingPart,
    'Product 27',
    '$66.23',
    '19',
    '7.45 kg',
  ),
  createData(
    'https://via.placeholder.com/150',
    '67 cm',
    'Plastic',
    MaterialType.ManufactoringPart,
    'Product 28',
    '$50.34',
    '80',
    '6.67 kg',
  ),
  createData(
    'https://via.placeholder.com/150',
    '23 cm',
    'Metal',
    MaterialType.Product,
    'Product 29',
    '$21.45',
    '93',
    '2.89 kg',
  ),
  createData(
    'https://via.placeholder.com/150',
    '56 cm',
    'Wood',
    MaterialType.PurchasingPart,
    'Product 30',
    '$44.78',
    '61',
    '5.12 kg',
  ),
  createData(
    'https://via.placeholder.com/150',
    '78 cm',
    'Plastic',
    MaterialType.ManufactoringPart,
    'Product 31',
    '$76.23',
    '48',
    '7.89 kg',
  ),
  createData(
    'https://via.placeholder.com/150',
    '45 cm',
    'Metal',
    MaterialType.Product,
    'Product 32',
    '$34.56',
    '55',
    '4.45 kg',
  ),
  createData(
    'https://via.placeholder.com/150',
    '12 cm',
    'Wood',
    MaterialType.PurchasingPart,
    'Product 33',
    '$12.34',
    '87',
    '1.56 kg',
  ),
  createData(
    'https://via.placeholder.com/150',
    '90 cm',
    'Plastic',
    MaterialType.ManufactoringPart,
    'Product 34',
    '$89.78',
    '20',
    '8.12 kg',
  ),
  createData(
    'https://via.placeholder.com/150',
    '67 cm',
    'Metal',
    MaterialType.Product,
    'Product 35',
    '$63.45',
    '71',
    '6.34 kg',
  ),
  createData(
    'https://via.placeholder.com/150',
    '34 cm',
    'Wood',
    MaterialType.PurchasingPart,
    'Product 36',
    '$30.23',
    '99',
    '3.78 kg',
  ),
  createData(
    'https://via.placeholder.com/150',
    '23 cm',
    'Plastic',
    MaterialType.ManufactoringPart,
    'Product 37',
    '$20.45',
    '58',
    '2.12 kg',
  ),
  createData(
    'https://via.placeholder.com/150',
    '56 cm',
    'Metal',
    MaterialType.Product,
    'Product 38',
    '$48.56',
    '77',
    '4.89 kg',
  ),
  createData(
    'https://via.placeholder.com/150',
    '45 cm',
    'Wood',
    MaterialType.PurchasingPart,
    'Product 39',
    '$27.34',
    '50',
    '3.23 kg',
  ),
  createData(
    'https://via.placeholder.com/150',
    '78 cm',
    'Plastic',
    MaterialType.ManufactoringPart,
    'Product 40',
    '$75.67',
    '64',
    '7.45 kg',
  ),
  createData(
    'https://via.placeholder.com/150',
    '12 cm',
    'Metal',
    MaterialType.Product,
    'Product 41',
    '$14.78',
    '89',
    '1.67 kg',
  ),
  createData(
    'https://via.placeholder.com/150',
    '90 cm',
    'Wood',
    MaterialType.PurchasingPart,
    'Product 42',
    '$94.56',
    '42',
    '9.12 kg',
  ),
  createData(
    'https://via.placeholder.com/150',
    '34 cm',
    'Plastic',
    MaterialType.ManufactoringPart,
    'Product 43',
    '$33.45',
    '86',
    '3.56 kg',
  ),
  createData(
    'https://via.placeholder.com/150',
    '45 cm',
    'Metal',
    MaterialType.Product,
    'Product 44',
    '$35.89',
    '91',
    '4.23 kg',
  ),
  createData(
    'https://via.placeholder.com/150',
    '67 cm',
    'Wood',
    MaterialType.PurchasingPart,
    'Product 45',
    '$53.78',
    '25',
    '6.45 kg',
  ),
  createData(
    'https://via.placeholder.com/150',
    '78 cm',
    'Plastic',
    MaterialType.ManufactoringPart,
    'Product 46',
    '$79.12',
    '63',
    '7.67 kg',
  ),
  createData(
    'https://via.placeholder.com/150',
    '23 cm',
    'Metal',
    MaterialType.Product,
    'Product 47',
    '$26.34',
    '72',
    '2.45 kg',
  ),
];

export const productData = data.filter((row) => {
  return row.materialType === MaterialType.Product;
});

export const purchasingData = data.filter((row) => {
  return row.materialType === MaterialType.PurchasingPart;
});

export const manufactoringData = data.filter((row) => {
  return row.materialType === MaterialType.ManufactoringPart;
});

const columnHelper = createColumnHelper<IProduct>();

export const columns = [
  columnHelper.accessor('name', {
    header: 'Name',
    cell: ({ row }) => {
      const { imageUrl, name } = row.original;

      return (
        <Box display="flex" alignItems="center">
          <img src={imageUrl} alt={name} height={24} width={38} />
          <Typography>{name}</Typography>
        </Box>
      );
    },
  }),
  columnHelper.accessor('height', {
    header: 'Height',
    cell: ({ getValue }) => {
      return getValue();
    },
  }),
  columnHelper.accessor('material', {
    header: 'Material',
    cell: ({ getValue }) => {
      return getValue();
    },
  }),
  columnHelper.accessor('weight', {
    header: 'Weight',
    cell: ({ getValue }) => {
      return getValue();
    },
  }),
  columnHelper.accessor('stock', {
    header: 'Stock',
    cell: ({ getValue }) => {
      return getValue();
    },
  }),
  columnHelper.accessor('price', {
    header: 'Price',
    cell: ({ getValue }) => {
      return getValue();
    },
  }),
];
