export interface IProductData {
  materialType: IMaterialType[keyof IMaterialType];
  imageUrl: string;
  name: string;
  height: string;
  material: string;
  weight: string;
  stock: string;
  price: string;
}

interface IMaterialType {
  ManufactoringPart: 'manufactoring-part';
  Product: 'product';
  PurchasingPart: 'purchasing-part';
}

// eslint-disable-next-line func-style
export const createData = (
  materialType: IMaterialType[keyof IMaterialType],
  imageUrl: string,
  name: string,
  height: string,
  material: string,
  weight: string,
  stock: string,
  price: string,
): IProductData => {
  return {
    materialType,
    imageUrl,
    name,
    height,
    material,
    weight,
    stock,
    price,
  };
};

export const rows: IProductData[] = [
  createData(
    'product',
    'https://www.zeka.ba/media/3a/01/a1/1714395695/djeCije-biciklo-ty-952-16-17887.jpg',
    'Bicikl Cube 710 Hidraulika',
    '58 cm',
    'Carbon',
    '8,57 kg',
    '4 Stk.',
    '1689,99 €',
  ),
  createData(
    'product',
    'https://prox.ba/wp-content/uploads/2023/06/c12_featured-copy.jpg',
    'Biciklo BH01-106 Ability 29 21',
    '58 cm',
    'Alu',
    '12,57 kg',
    '8 Stk.',
    '1229,99 €',
  ),
  createData(
    'product',
    'https://bracom.ba/wp-content/uploads/2023/12/ALPINA-Biciklo-DOROTHY-26-6v-torbica-5.jpg',
    'Bicikl Hidraulic SMALL',
    '58 cm',
    'Carbon',
    '3,57 kg',
    '8 Stk.',
    '229,99 €',
  ),
  createData(
    'product',
    'https://triomax.ba/wp-content/uploads/2021/04/BICIKLO-584-24.png',
    'BICIKLO TY 584-24 COLI',
    '58 cm',
    'Alu',
    '3,57 kg',
    '8 Stk.',
    '2139,99 €',
  ),
  createData(
    'product',
    'https://www.zeka.ba/media/3a/01/a1/1714395695/djeCije-biciklo-ty-952-16-17887.jpg',
    'Bicikl Cube 710 Hidraulika',
    '58 cm',
    'Carbon',
    '8,57 kg',
    '4 Stk.',
    '1689,99 €',
  ),
  createData(
    'product',
    'https://prox.ba/wp-content/uploads/2023/06/c12_featured-copy.jpg',
    'Biciklo BH01-106 Ability 29 21',
    '58 cm',
    'Alu',
    '12,57 kg',
    '8 Stk.',
    '1229,99 €',
  ),
  createData(
    'product',
    'https://bracom.ba/wp-content/uploads/2023/12/ALPINA-Biciklo-DOROTHY-26-6v-torbica-5.jpg',
    'Bicikl Hidraulic SMALL',
    '58 cm',
    'Carbon',
    '3,57 kg',
    '8 Stk.',
    '229,99 €',
  ),
  createData(
    'product',
    'https://triomax.ba/wp-content/uploads/2021/04/BICIKLO-584-24.png',
    'BICIKLO TY 584-24 COLI',
    '58 cm',
    'Alu',
    '3,57 kg',
    '8 Stk.',
    '2139,99 €',
  ),
  createData(
    'product',
    'https://www.cungu.com/wp-content/uploads/2023/04/biciklooo.webp',
    'BICIKLO X2212102 - Cungu&Co',
    '58 cm',
    'Carbon',
    '3,57 kg',
    '8 Stk.',
    '139,99 €',
  ),
  createData(
    'product',
    'https://www.salcano.ba/wp-content/uploads/2022/08/ASTRO-S-275HD.jpg',
    'Biciklo Salcano ASTRO S 275HD - Salcano',
    '58 cm',
    'Alu',
    '9,57 kg',
    '1 Stk.',
    '839,99 €',
  ),
  createData(
    'product',
    'https://yekupi.blob.core.windows.net/ekupiba/1200Wx1200H/EK000370808_1.image',
    'CROSS SPEEDSTER 24',
    '58 cm',
    'Alu',
    '9,57 kg',
    '1 Stk.',
    '8329,99 €',
  ),
  createData(
    'product',
    'https://triomax.ba/wp-content/uploads/2021/03/BICIKLO-569-26.png',
    'BICIKLO TY 569-24',
    '58 cm',
    'Alu',
    '9,57 kg',
    '1 Stk.',
    '234,99 €',
  ),
  createData(
    'product',
    'https://moccacommerce.com/wp-content/uploads/2023/07/Biciklo-Polar-P202S03233-JR-Unicorn1.webp',
    'Polar Biciklo 18" Unicorn JR',
    '58 cm',
    'Alu',
    '9,57 kg',
    '1 Stk.',
    '234,99 €',
  ),
  createData(
    'product',
    'https://grmec.me/keshirano/proizvodi/tmb_800_800_wy7lfxk7fjkskw.png',
    'Visitor NITRO 29/18-1280151 - GRMEČ - WEBSHOP',
    '58 cm',
    'Alu',
    '9,57 kg',
    '1 Stk.',
    '2324,99 €',
  ),
  createData(
    'product',
    'https://www.capriolo.com/sites/default/files/291091.png',
    'GIMFIT SOBNO BICIKLO 291091 ',
    '58 cm',
    'Alu',
    '9,57 kg',
    '1 Stk.',
    '2324,99 €',
  ),
  createData(
    'manufactoring-part',
    'https://image.made-in-china.com/202f0j00YdwTVqWhYUru/Manufacturing-Part-CNC-Milling-Machining-Service-Spare-Parts.jpg',
    'Manufacturing Part CNC Milling Machining Service Spare Parts',
    '58 cm',
    'Alu',
    '9,57 kg',
    '1 Stk.',
    '839,99 €',
  ),
  createData(
    'manufactoring-part',
    'https://www.sciaky.com/images/content/thumbs/titanium-parts.jpg',
    'Additive Manufacturing of Titanium Parts ',
    '58 cm',
    'Alu',
    '9,57 kg',
    '1 Stk.',
    '839,99 €',
  ),
  createData(
    'manufactoring-part',
    'https://image.made-in-china.com/202f0j00jEYohWHlVTpV/High-Precision-Metal-Auto-Hardware-Parts-Custom-Turning-CNC-Machining-CNC-Manufacturing-Part.webp',
    'High Precision Metal Auto Hardware Parts',
    '58 cm',
    'Alu',
    '9,57 kg',
    '1 Stk.',
    '839,99 €',
  ),
  createData(
    'manufactoring-part',
    'https://image.made-in-china.com/202f0j00jEYohWHlVTpV/High-Precision-Metal-Auto-Hardware-Parts-Custom-Turning-CNC-Machining-CNC-Manufacturing-Part.webp',
    'High Precision Metal Auto Hardware Parts',
    '58 cm',
    'Alu',
    '9,57 kg',
    '1 Stk.',
    '839,99 €',
  ),
  createData(
    'manufactoring-part',
    'https://www.protolabs.com/media/1021019/metal-3dp-assembly-570x308.png?width=570&height=308&rnd=132417130663230000',
    'Guide to Part Consolidation for Additive Manufacturing',
    '58 cm',
    'Alu',
    '9,57 kg',
    '1 Stk.',
    '839,99 €',
  ),
  createData(
    'manufactoring-part',
    'https://www.sciaky.com/images/content/thumbs/steel-piston_finalCOMP-thumb.jpg',
    'Additive Manufacturing Services',
    '58 cm',
    'Alu',
    '9,57 kg',
    '1 Stk.',
    '839,99 €',
  ),
  createData(
    'manufactoring-part',
    'https://image.made-in-china.com/202f0j00nafoiWICsTzl/High-Precision-Metal-Auto-Hardware-Parts-Custom-Turning-CNC-Machining-CNC-Manufacturing-Part.webp',
    'High Precision Metal Auto Hardware Parts',
    '58 cm',
    'Alu',
    '9,57 kg',
    '1 Stk.',
    '839,99 €',
  ),
  createData(
    'manufactoring-part',
    'https://image.made-in-china.com/202f0j00YdwTVqWhYUru/Manufacturing-Part-CNC-Milling-Machining-Service-Spare-Parts.jpg',
    'Manufacturing Part CNC Milling Machining Service Spare Parts',
    '58 cm',
    'Alu',
    '9,57 kg',
    '1 Stk.',
    '839,99 €',
  ),
  createData(
    'manufactoring-part',
    'https://www.sciaky.com/images/content/thumbs/titanium-parts.jpg',
    'Additive Manufacturing of Titanium Parts ',
    '58 cm',
    'Alu',
    '9,57 kg',
    '1 Stk.',
    '839,99 €',
  ),
  createData(
    'manufactoring-part',
    'https://image.made-in-china.com/202f0j00jEYohWHlVTpV/High-Precision-Metal-Auto-Hardware-Parts-Custom-Turning-CNC-Machining-CNC-Manufacturing-Part.webp',
    'High Precision Metal Auto Hardware Parts',
    '58 cm',
    'Alu',
    '9,57 kg',
    '1 Stk.',
    '839,99 €',
  ),
  createData(
    'manufactoring-part',
    'https://image.made-in-china.com/202f0j00jEYohWHlVTpV/High-Precision-Metal-Auto-Hardware-Parts-Custom-Turning-CNC-Machining-CNC-Manufacturing-Part.webp',
    'High Precision Metal Auto Hardware Parts',
    '58 cm',
    'Alu',
    '9,57 kg',
    '1 Stk.',
    '839,99 €',
  ),
  createData(
    'manufactoring-part',
    'https://www.protolabs.com/media/1021019/metal-3dp-assembly-570x308.png?width=570&height=308&rnd=132417130663230000',
    'Guide to Part Consolidation for Additive Manufacturing',
    '58 cm',
    'Alu',
    '9,57 kg',
    '1 Stk.',
    '839,99 €',
  ),
  createData(
    'manufactoring-part',
    'https://www.sciaky.com/images/content/thumbs/steel-piston_finalCOMP-thumb.jpg',
    'Additive Manufacturing Services',
    '58 cm',
    'Alu',
    '9,57 kg',
    '1 Stk.',
    '839,99 €',
  ),
  createData(
    'manufactoring-part',
    'https://image.made-in-china.com/202f0j00nafoiWICsTzl/High-Precision-Metal-Auto-Hardware-Parts-Custom-Turning-CNC-Machining-CNC-Manufacturing-Part.webp',
    'High Precision Metal Auto Hardware Parts',
    '58 cm',
    'Alu',
    '9,57 kg',
    '1 Stk.',
    '839,99 €',
  ),
  createData(
    'purchasing-part',
    'https://image.made-in-china.com/202f0j00jEYohWHlVTpV/High-Precision-Metal-Auto-Hardware-Parts-Custom-Turning-CNC-Machining-CNC-Manufacturing-Part.webp',
    'High Precision Metal Auto Hardware Parts',
    '58 cm',
    'Alu',
    '9,57 kg',
    '1 Stk.',
    '839,99 €',
  ),
  createData(
    'purchasing-part',
    'https://image.made-in-china.com/202f0j00nafoiWICsTzl/High-Precision-Metal-Auto-Hardware-Parts-Custom-Turning-CNC-Machining-CNC-Manufacturing-Part.webp',
    'High Precision Metal Auto Hardware Parts',
    '58 cm',
    'Alu',
    '9,57 kg',
    '1 Stk.',
    '839,99 €',
  ),
  createData(
    'purchasing-part',
    'https://image.made-in-china.com/202f0j00jEYohWHlVTpV/High-Precision-Metal-Auto-Hardware-Parts-Custom-Turning-CNC-Machining-CNC-Manufacturing-Part.webp',
    'High Precision Metal Auto Hardware Parts',
    '58 cm',
    'Alu',
    '9,57 kg',
    '1 Stk.',
    '839,99 €',
  ),
  createData(
    'purchasing-part',
    'https://www.sciaky.com/images/content/thumbs/titanium-parts.jpg',
    'Additive Manufacturing of Titanium Parts ',
    '58 cm',
    'Alu',
    '9,57 kg',
    '1 Stk.',
    '839,99 €',
  ),
  createData(
    'purchasing-part',
    'https://image.made-in-china.com/202f0j00nafoiWICsTzl/High-Precision-Metal-Auto-Hardware-Parts-Custom-Turning-CNC-Machining-CNC-Manufacturing-Part.webp',
    'High Precision Metal Auto Hardware Parts',
    '58 cm',
    'Alu',
    '9,57 kg',
    '1 Stk.',
    '839,99 €',
  ),
  createData(
    'purchasing-part',
    'https://www.sciaky.com/images/content/thumbs/steel-piston_finalCOMP-thumb.jpg',
    'Additive Manufacturing Services',
    '58 cm',
    'Alu',
    '9,57 kg',
    '1 Stk.',
    '839,99 €',
  ),
  createData(
    'purchasing-part',
    'https://image.made-in-china.com/202f0j00nafoiWICsTzl/High-Precision-Metal-Auto-Hardware-Parts-Custom-Turning-CNC-Machining-CNC-Manufacturing-Part.webp',
    'High Precision Metal Auto Hardware Parts',
    '58 cm',
    'Alu',
    '9,57 kg',
    '1 Stk.',
    '839,99 €',
  ),
  createData(
    'purchasing-part',
    'https://image.made-in-china.com/202f0j00nafoiWICsTzl/High-Precision-Metal-Auto-Hardware-Parts-Custom-Turning-CNC-Machining-CNC-Manufacturing-Part.webp',
    'High Precision Metal Auto Hardware Parts',
    '58 cm',
    'Alu',
    '9,57 kg',
    '1 Stk.',
    '839,99 €',
  ),
  createData(
    'purchasing-part',
    'https://image.made-in-china.com/202f0j00YdwTVqWhYUru/Manufacturing-Part-CNC-Milling-Machining-Service-Spare-Parts.jpg',
    'Manufacturing Part CNC Milling Machining Service Spare Parts',
    '58 cm',
    'Alu',
    '9,57 kg',
    '1 Stk.',
    '839,99 €',
  ),
  createData(
    'purchasing-part',
    'https://www.sciaky.com/images/content/thumbs/titanium-parts.jpg',
    'Additive Manufacturing of Titanium Parts ',
    '58 cm',
    'Alu',
    '9,57 kg',
    '1 Stk.',
    '839,99 €',
  ),
];
