import { tss } from '@/styles/theme';

export const useStyles = tss.create(({ theme }) => {
  return {
    wrapper: {
      display: 'flex',
      flexDirection: 'column',
      width: '30%',
      position: 'absolute',
      top: '50%',
      left: '50%',
      transform: 'translate(-50%, -50%)',
      border: `1px solid ${theme.palette.border.primary}`,
      backgroundColor: theme.palette.white.primary,
      borderRadius: '16px',
    },
    header: {
      width: '100%',
      display: 'flex',
      flexDirection: 'column',
      justifyContent: 'space-between',
      alignItems: 'center',
      padding: '8px 16px 0 16px',
      gap: '12px',
    },
    text: {
      display: 'flex',
      flexDirection: 'column',
      gap: '4px',
    },
    title: {
      width: '100%',
      fontWeight: theme.typography.fontWeight.medium,
      fontSize: '1rem',
      color: theme.palette.text.primary,
      lineHeight: 1.5,
      textAlign: 'center',
    },
    subtitle: {
      width: '100%',
      fontWeight: theme.typography.fontWeight.regular,
      fontSize: '0.875rem',
      color: theme.palette.main.primary,
      lineHeight: 1.5,
      textAlign: 'center',
    },
    footer: {
      display: 'flex',
      padding: '12px 16px',
      gap: '12px',
    },
    deleteButton: {
      width: '100%',
      height: '40px',
      borderRadius: '12px',
      padding: '8px 16px',
      textTransform: 'none',
      fontWeight: theme.typography.fontWeight.medium,
      fontSize: '0.875rem',
      lineHeight: 1.25,
      border: `1px solid ${theme.palette.border.primary}`,
      backgroundColor: theme.palette.white.primary,
      color: 'red',
      '&:hover': {
        backgroundColor: theme.palette.white.secondary,
      },
    },
    cancelButton: {
      width: '100%',
      height: '40px',
      borderRadius: '12px',
      padding: '8px 16px',
      textTransform: 'none',
      fontWeight: theme.typography.fontWeight.medium,
      fontSize: '0.875rem',
      lineHeight: 1.25,
      border: `1px solid ${theme.palette.border.primary}`,
      backgroundColor: theme.palette.white.primary,
      color: theme.palette.text.primary,
      '&:hover': {
        backgroundColor: theme.palette.white.secondary,
      },
    },
    deleteIcon: {
      height: '40px',
      width: '40px',
      background: '#FEF3F2',
      '& svg path': {
        stroke: '#F04438',
      },
    },
    iconContainer: {
      height: '44px',
      width: '100%',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'end',
      padding: '18px 22px 6px 0',
      '& .MuiIconButton-root': {
        padding: 0,
      },
    },
    closeIcon: {},
  };
});
